name: flutter_token_auth
description: A package for handling token-based authentication in Flutter.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test: ^1.25.0
  flutter_test:
    sdk: flutter
